version: "3.8"

volumes:
  pg_data:
  static_volume:
  media_volume:
  pgadmin:


services:
  db:
    image: postgres:14.10
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    container_name: backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    env_file: 
      - .env
    
    volumes:
      - static_volume:/static/backend_static/
      - media_volume:/media/images/
    
  pgadmin:
    depends_on:
      - db
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    
    
    restart: unless-stopped

  gateway:
    depends_on:
      - backend
    container_name: nginx
    build: ./nginx/
    env_file: .env
    
    ports:
      - 8000:80
    volumes:
      - static_volume:/static/backend_static/
      - media_volume:/media/images/




 