# Generated by Django 4.2.8 on 2023-12-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("direction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profession",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание"
            ),
        ),
    ]
