# Generated by Django 4.2.7 on 2023-12-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('direction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professionindirection',
            options={'verbose_name': 'Профессия в направления', 'verbose_name_plural': 'Професcии в направлениях'},
        ),
        migrations.AlterField(
            model_name='professionindirection',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professions', to='direction.profession', verbose_name='Професcии'),
        ),
    ]
