# Generated by Django 4.2.7 on 2023-12-03 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("direction", "0004_remove_direction_courses_dir_course_direction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="direction",
            name="link",
        ),
    ]
