# Generated by Django 4.2.7 on 2023-12-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("direction", "0005_remove_direction_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="link",
            field=models.SlugField(
                blank=True, unique=True, verbose_name="Адрес"
            ),
        ),
    ]
