# Generated by Django 4.2.7 on 2023-12-03 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("direction", "0006_alter_course_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="direction",
        ),
        migrations.AddField(
            model_name="course",
            name="professions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profession",
                to="direction.profession",
                verbose_name="Профессии курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("newbie", "Без опыта"),
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                ],
                default=None,
                max_length=256,
                verbose_name="Уровень",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="link",
            field=models.SlugField(blank=True, verbose_name="Адрес"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название"),
        ),
    ]
