# Generated by Django 4.2.8 on 2023-12-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "direction",
            "0007_remove_course_direction_course_professions_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="professionindirection",
            options={
                "verbose_name": "Профессия в направления",
                "verbose_name_plural": "Професcии в направлениях",
            },
        ),
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="profession",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="images/", verbose_name="Изображение"
            ),
        ),
        migrations.AlterField(
            model_name="professionindirection",
            name="profession",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professions",
                to="direction.profession",
                verbose_name="Професcии",
            ),
        ),
    ]
