# Generated by Django 4.2.8 on 2023-12-05 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("direction", "0008_alter_professionindirection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="professions",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profession",
                to="direction.profession",
                verbose_name="Профессии курса",
            ),
            preserve_default=False,
        ),
    ]
