# Generated by Django 4.2.7 on 2023-12-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergrademap",
            name="end_level",
            field=models.CharField(
                choices=[
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                ],
                verbose_name="Квалификация",
            ),
        ),
        migrations.AlterField(
            model_name="usergrademap",
            name="start_level",
            field=models.CharField(
                choices=[
                    ("newbie", "Без опыта"),
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                ],
                verbose_name="Квалификация",
            ),
        ),
    ]
