# Generated by Django 4.2.8 on 2023-12-06 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0003_alter_user_courses_alter_usergrademap_end_prof_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email"
            ),
        ),
        migrations.AlterField(
            model_name="usergrademap",
            name="end_level",
            field=models.CharField(
                choices=[
                    ("junior", "Junior"),
                    ("middle", "Middle"),
                    ("senior", "Senior"),
                    ("lead", "Lead"),
                ],
                verbose_name="Желаемая квалификация",
            ),
        ),
        migrations.AlterField(
            model_name="usergrademap",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
